# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_iscomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(default='False'),
        ),
    ]
