# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160218_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(),
        ),
    ]
